apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: wazuh-events
  namespace: wazuh
spec:
  entryPoints:
    - wazuh-1514
  routes:
  - match: HostSNI(`*`)
    services:
    - name: wazuh-events
      port: 1514
