apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: wazuh-registration
  namespace: wazuh
spec:
  entryPoints:
    - wazuh-1515
  routes:
  - match: HostSNI(`*`)
    services:
    - name: wazuh-registration
      port: 1515
