apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wazuh-api-ingress
  namespace: wazuh
spec:
  podSelector:
    matchLabels:
      app: wazuh-manager
      node-type: master
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: wazuh-dashboard
    ports:
    - protocol: TCP
      port: 55000
  - from:
    - podSelector:
        matchLabels:
          app: wazuh-manager
    ports:
    - protocol: TCP
      port: 1516
