# Copyright (C) 2021 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

bases:
  - ../../wazuh
patches:
  - storage-class.yaml
  - elastic-resources.yaml
  - wazuh-resources.yaml
