[book]
title = "Wazuh Kubernetes Documentation"
description = "The technical documentation for Wazuh Kubernetes deployment method, composed by the development documentation and the reference manual."
authors = ["Wazuh DevOps Team"]
language = "en"
src = "."
